package com.amcglynn.myzappi.handlers;

import com.amazon.ask.dispatcher.request.handler.HandlerInput;
import com.amazon.ask.dispatcher.request.handler.RequestHandler;
import com.amazon.ask.model.Response;
import com.amazon.ask.model.interfaces.alexa.presentation.apl.RenderDocumentDirective;
import com.amazon.ask.request.RequestHelper;
import com.amcglynn.myzappi.UserIdResolverFactory;
import com.amcglynn.myzappi.UserZoneResolver;
import com.amcglynn.myzappi.core.Brand;
import com.amcglynn.myzappi.core.service.MyEnergiService;
import com.amcglynn.myzappi.service.EnergyUsageGraphGenerator;
import com.amcglynn.myzappi.service.S3Service;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;

import static com.amazon.ask.request.Predicates.intentName;
import static com.amcglynn.myzappi.LocalisedResponse.cardResponse;
import static com.amcglynn.myzappi.LocalisedResponse.voiceResponse;

@Slf4j
public class GetEnergyUsageGraphHandler implements RequestHandler {

    private final MyEnergiService.Builder zappyServiceBuilder;
    private final UserIdResolverFactory userIdResolverFactory;
    private final UserZoneResolver userZoneResolver;
    private final S3Service s3Service;
    private static final String BUCKET_NAME = "myzappi-autogenerated-graphs";

    public GetEnergyUsageGraphHandler(MyEnergiService.Builder zappyServiceBuilder, UserIdResolverFactory userIdResolverFactory,
                                      UserZoneResolver userZoneResolver) {
        this.zappyServiceBuilder = zappyServiceBuilder;
        this.userIdResolverFactory = userIdResolverFactory;
        this.userZoneResolver = userZoneResolver;
        s3Service = new S3Service();
    }

    @Override
    public boolean canHandle(HandlerInput handlerInput) {
        return handlerInput.matches(intentName("GetEnergyUsageGraph"));
    }

    @SneakyThrows
    @Override
    public Optional<Response> handle(HandlerInput handlerInput) {
        if (!hasDisplayInterface(handlerInput)) {
            return handlerInput.getResponseBuilder()
                    .withSpeech(voiceResponse(handlerInput, "graph-not-supported"))
                    .withSimpleCard(Brand.NAME,
                            cardResponse(handlerInput, "graph-not-supported"))
                    .withShouldEndSession(true)
                    .build();
        }

        var locale = Locale.forLanguageTag(handlerInput.getRequestEnvelope().getRequest().getLocale());
        // expected date format is 2023-05-06
        var date = parseDate(handlerInput);
        if (date.isPresent() && date.get().length() != 10) {
            return getInvalidInputResponse(handlerInput);
        }

        var userTimeZone = userZoneResolver.getZoneId(handlerInput);
        var localDate = date.map(d -> LocalDate.parse(d, DateTimeFormatter.ISO_DATE))
                .orElse(LocalDate.now(userTimeZone));

        if (isInvalid(localDate, userTimeZone)) {
            return getInvalidRequestedDateResponse(handlerInput);
        }

        var zappiService = zappyServiceBuilder.build(userIdResolverFactory.newUserIdResolver(handlerInput)).getZappiServiceOrThrow();
        var history = zappiService.getRawEnergyHistory(localDate, userTimeZone);

        var imageContent = new EnergyUsageGraphGenerator().generateGraph(history);
        final var s3KeyName = handlerInput.getRequestEnvelope().getSession().getSessionId() + ".png";
        s3Service.uploadToS3(BUCKET_NAME,
                s3KeyName, imageContent, "image/png");
        var presignedUrl = s3Service.generatePresignUrl(BUCKET_NAME, s3KeyName, Duration.ofMinutes(10));

        RenderDocumentDirective renderDocumentDirective = RenderDocumentDirective.builder()
                .withToken("zappidaysummaryToken")
                .withDocument(buildDocument(presignedUrl.toString()))
                .build();

        return handlerInput.getResponseBuilder()
                .withSpeech("Here's your graph")
                .withSimpleCard("My Zappi", "Checkout the graph")
                .addDirective(renderDocumentDirective)
                .withShouldEndSession(false)
                .build();
    }

    @SneakyThrows
    private Map<String, Object> buildDocument(String imageSourceUrl) {
        ObjectMapper mapper = new ObjectMapper();
        TypeReference<HashMap<String, Object>> documentMapType = new TypeReference<>() {
        };

        InputStream inputStream = GetEnergyUsageGraphHandler.class.getClassLoader().getResourceAsStream("apl-energy-usage-graph.json");

        var contents = new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);

        contents = contents.replace("${payload.backgroundEnergyUsageGraph}", imageSourceUrl);

        return mapper.readValue(contents, documentMapType);
    }

    private boolean hasDisplayInterface(HandlerInput handlerInput) {
        return RequestHelper.forHandlerInput(handlerInput)
                .getSupportedInterfaces()
                .getAlexaPresentationAPL() != null;
    }

    private Optional<Response> getInvalidRequestedDateResponse(HandlerInput handlerInput) {
        return handlerInput.getResponseBuilder()
                .withSpeech(voiceResponse(handlerInput, "invalid-future-date"))
                .withSimpleCard(Brand.NAME,
                        cardResponse(handlerInput, "invalid-future-date"))
                .withShouldEndSession(false)
                .build();
    }

    private Optional<Response> getInvalidInputResponse(HandlerInput handlerInput) {
        return handlerInput.getResponseBuilder()
                .withSpeech(voiceResponse(handlerInput, "request-specific-date"))
                .withSimpleCard(Brand.NAME,
                        cardResponse(handlerInput, "request-specific-date"))
                .withShouldEndSession(false)
                .build();
    }

    /**
     * Invalid if date is in the future. Requesting for today is accepted but not future dates.
     * @param date today or historical date
     * @param userTimeZone time-zone of the user
     * @return true if invalid
     */
    private boolean isInvalid(LocalDate date, ZoneId userTimeZone) {
        return date.isAfter(LocalDate.now(userTimeZone));
    }

    private Optional<String> parseDate(HandlerInput handlerInput) {
        return RequestHelper.forHandlerInput(handlerInput)
                .getSlotValue("date");
    }
}
