package com.amcglynn.myzappi.service;

import com.amazon.ask.dispatcher.request.handler.HandlerInput;

import java.net.URL;
import java.time.Duration;
import java.util.UUID;

public class GraphManagementService {

    private static final String BUCKET_NAME = "myzappi-autogenerated-graphs";
    private S3Service s3Service;

    public GraphManagementService(S3Service s3Service) {
        this.s3Service = s3Service;
    }

    public URL saveGraph(HandlerInput handlerInput, byte[] imageContent) {
        final var s3KeyName = resolveS3KeyName(handlerInput);
        s3Service.uploadToS3(BUCKET_NAME,
                s3KeyName, imageContent, "image/png");
        return s3Service.generatePresignUrl(BUCKET_NAME, s3KeyName, Duration.ofMinutes(10));
    }

    private String resolveS3KeyName(HandlerInput handlerInput) {
        return handlerInput.getRequestEnvelope().getSession().getUser().getUserId() + ".png";
    }
}
